import 'dart:js_interop';

import 'package:web/web.dart';

/// Layered game-style answer feedback generated by the browser.
///
/// Generating the tones at runtime avoids an audio asset download and keeps
/// quiz feedback available on Flutter Web without a new package dependency.
abstract final class QuizFeedbackSound {
  static AudioContext? _context;

  /// Initializes the browser audio context while the submit button still has
  /// the user's activation. Browsers otherwise commonly block later playback.
  static Future<void> prime() async {
    try {
      final context = _context ??= AudioContext();
      await context.resume().toDart;
    } on Object {
      // Audio feedback is optional; a blocked or unavailable browser context
      // must never prevent an answer from being submitted.
    }
  }

  static Future<void> play({required bool isCorrect}) async {
    await prime();
    final context = _context;
    if (context == null) return;

    final notes = isCorrect ? _victoryNotes : _missNotes;

    for (final note in notes) {
      _scheduleTone(context, note);
    }
  }

  static void _scheduleTone(AudioContext context, _Tone note) {
    final startAt = context.currentTime + note.delay;
    final endAt = startAt + note.duration;
    final oscillator = context.createOscillator();
    final gain = context.createGain();

    oscillator.type = note.waveform;
    oscillator.frequency.setValueAtTime(note.frequency, startAt);
    if (note.endFrequency != null) {
      oscillator.frequency.exponentialRampToValueAtTime(
        note.endFrequency!,
        endAt,
      );
    }
    gain.gain
      ..setValueAtTime(.0001, startAt)
      ..exponentialRampToValueAtTime(note.volume, startAt + .025)
      ..exponentialRampToValueAtTime(.0001, endAt);
    oscillator
      ..connect(gain)
      ..start(startAt)
      ..stop(endAt);
    gain.connect(context.destination);
  }

  // A 2.6 second, layered major-key fanfare: rising arpeggio, chord bed and
  // bright bell notes. Kept below speech-level volume to respect the learner.
  static const _victoryNotes = <_Tone>[
    _Tone(frequency: 523.25, delay: 0, duration: .34, volume: .07),
    _Tone(frequency: 659.25, delay: .18, duration: .36, volume: .08),
    _Tone(frequency: 783.99, delay: .36, duration: .42, volume: .09),
    _Tone(frequency: 1046.5, delay: .56, duration: .62, volume: .1),
    _Tone(
      frequency: 261.63,
      delay: .54,
      duration: 1.45,
      volume: .035,
      waveform: 'triangle',
    ),
    _Tone(
      frequency: 329.63,
      delay: .54,
      duration: 1.45,
      volume: .03,
      waveform: 'triangle',
    ),
    _Tone(
      frequency: 392,
      delay: .54,
      duration: 1.45,
      volume: .03,
      waveform: 'triangle',
    ),
    _Tone(frequency: 1318.51, delay: .82, duration: .32, volume: .045),
    _Tone(frequency: 1567.98, delay: 1.08, duration: .38, volume: .04),
    _Tone(
      frequency: 523.25,
      delay: 1.55,
      duration: 1.05,
      volume: .06,
      waveform: 'triangle',
    ),
    _Tone(
      frequency: 659.25,
      delay: 1.55,
      duration: 1.05,
      volume: .055,
      waveform: 'triangle',
    ),
    _Tone(frequency: 783.99, delay: 1.55, duration: 1.05, volume: .055),
    _Tone(frequency: 1567.98, delay: 1.8, duration: .72, volume: .035),
  ];

  // A gentle 1.7 second descending motif. The soft sine bass gives it a
  // disappointed, never harsh, game-over character.
  static const _missNotes = <_Tone>[
    _Tone(
      frequency: 392,
      endFrequency: 349.23,
      delay: 0,
      duration: .42,
      volume: .065,
      waveform: 'triangle',
    ),
    _Tone(
      frequency: 329.63,
      endFrequency: 293.66,
      delay: .3,
      duration: .46,
      volume: .06,
      waveform: 'triangle',
    ),
    _Tone(
      frequency: 261.63,
      endFrequency: 220,
      delay: .62,
      duration: .72,
      volume: .055,
      waveform: 'triangle',
    ),
    _Tone(
      frequency: 196,
      delay: .14,
      duration: 1.55,
      volume: .025,
      waveform: 'sine',
    ),
  ];
}

class _Tone {
  const _Tone({
    required this.frequency,
    required this.delay,
    required this.duration,
    required this.volume,
    this.endFrequency,
    this.waveform = 'sine',
  });

  final num frequency;
  final num? endFrequency;
  final num delay;
  final num duration;
  final num volume;
  final String waveform;
}
