import 'dart:js_interop';

import 'package:web/web.dart';

/// Lightweight answer feedback sounds generated by the browser.
///
/// Generating the tones at runtime avoids an audio asset download and keeps
/// quiz feedback available on Flutter Web without a new package dependency.
abstract final class QuizFeedbackSound {
  static AudioContext? _context;

  /// Initializes the browser audio context while the submit button still has
  /// the user's activation. Browsers otherwise commonly block later playback.
  static Future<void> prime() async {
    try {
      final context = _context ??= AudioContext();
      await context.resume().toDart;
    } on Object {
      // Audio feedback is optional; a blocked or unavailable browser context
      // must never prevent an answer from being submitted.
    }
  }

  static Future<void> play({required bool isCorrect}) async {
    await prime();
    final context = _context;
    if (context == null) return;

    final notes = isCorrect
        ? const <_Tone>[
            _Tone(frequency: 660, delay: 0, duration: .12),
            _Tone(frequency: 880, delay: .14, duration: .18),
          ]
        : const <_Tone>[_Tone(frequency: 220, delay: 0, duration: .22)];

    for (final note in notes) {
      _scheduleTone(context, note);
    }
  }

  static void _scheduleTone(AudioContext context, _Tone note) {
    final startAt = context.currentTime + note.delay;
    final endAt = startAt + note.duration;
    final oscillator = context.createOscillator();
    final gain = context.createGain();

    oscillator.type = 'sine';
    oscillator.frequency.setValueAtTime(note.frequency, startAt);
    gain.gain
      ..setValueAtTime(.0001, startAt)
      ..exponentialRampToValueAtTime(.14, startAt + .02)
      ..exponentialRampToValueAtTime(.0001, endAt);
    oscillator
      ..connect(gain)
      ..start(startAt)
      ..stop(endAt);
    gain.connect(context.destination);
  }
}

class _Tone {
  const _Tone({
    required this.frequency,
    required this.delay,
    required this.duration,
  });

  final num frequency;
  final num delay;
  final num duration;
}
