-- Published Namsan Seoul Tower content. Travel information was checked on
-- 2026-10-04 and must be reconfirmed on the operator's website before travel.

do $$
declare
  location_uuid uuid := '00000000-0000-4000-8000-000000000300';
  revision_uuid uuid := '00000000-0000-4000-8000-000000000400';
begin
  insert into public.locations (id, slug)
  values (location_uuid, 'namsan')
  on conflict (slug) do nothing;

  select id into location_uuid from public.locations
  where slug = 'namsan';

  if not exists (
    select 1 from public.location_revisions
    where location_id = location_uuid and status = 'published'
  ) then
    insert into public.location_revisions (
      id, location_id, version_number, status, name, korean_name, english_name,
      address, city, region, country, latitude, longitude, location_type,
      short_description, long_description, cover_image_url, cover_image_credit,
      cover_image_source_url, cover_image_alt, hook_media_kind, hook_media_url,
      hook_media_credit, hook_media_source_url, hook_media_alt, hook_title,
      hook_caption, tags, categories, release_status, estimated_duration_minutes,
      display_order, stamp_name, stamp_description, stamp_image_url,
      stamp_image_credit, stamp_image_source_url, stamp_image_alt,
      experience_featured_fact, opening_hours, ticket_price, recommended_duration,
      best_time_to_visit, accessibility_info, travel_official_source_url,
      travel_last_verified_at
    ) values (
      revision_uuid, location_uuid, 1, 'published', 'Tháp Namsan Seoul', '남산서울타워', 'Namsan Seoul Tower',
      '105 Namsangongwon-gil, Yongsan-gu, Seoul 04340', 'Seoul', 'Yongsan-gu', 'Hàn Quốc',
      37.5513, 126.9882, 'Đài quan sát và tháp truyền phát',
      'Biểu tượng của Seoul trên đỉnh núi Namsan, kết hợp tháp phát sóng, đài quan sát và các trải nghiệm ngắm toàn cảnh thành phố.',
      'Namsan Seoul Tower, còn được biết đến là YTN Seoul Tower hoặc N Seoul Tower, đứng trên núi Namsan ở trung tâm Seoul. Công trình kết hợp chức năng truyền phát sóng với đài quan sát dành cho khách tham quan. Từ khu tháp, người học có thể kết nối câu chuyện về phát triển truyền thông Hàn Quốc với cảnh quan đô thị, công viên Namsan và cách một địa danh hiện đại trở thành biểu tượng thành phố. Hành trình giới thiệu lịch sử xây dựng, các không gian quan sát, cách tiếp cận bằng xe buýt, cáp treo hoặc đi bộ, cùng những quy tắc giúp tham quan an toàn và tôn trọng không gian chung.',
      'https://commons.wikimedia.org/wiki/Special:FilePath/N%20Seoul%20Tower%20%2813952097192%29.jpg',
      'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:N_Seoul_Tower_(13952097192).jpg',
      'Namsan Seoul Tower nhìn từ công viên Namsan', 'image',
      'https://commons.wikimedia.org/wiki/Special:FilePath/N%20Seoul%20Tower%20%2813952097192%29.jpg',
      'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:N_Seoul_Tower_(13952097192).jpg',
      'Namsan Seoul Tower trên đỉnh núi Namsan', 'Ngắm Seoul từ ngọn núi trung tâm',
      'Khám phá nơi thiên nhiên Namsan, công nghệ truyền phát và đường chân trời Seoul gặp nhau.',
      array['Seoul', 'Namsan', 'đài quan sát', 'toàn cảnh'], array['Cảnh quan', 'Công nghệ', 'Văn hóa đô thị'], 'released', 120, 2,
      'Dấu ấn toàn cảnh Seoul', 'Dấu mộc dành cho người hoàn thành hành trình khám phá Namsan Seoul Tower.',
      'https://commons.wikimedia.org/wiki/Special:FilePath/N%20Seoul%20Tower%20%2813952097192%29.jpg',
      'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:N_Seoul_Tower_(13952097192).jpg',
      'Tháp Namsan Seoul dùng làm biểu tượng dấu mộc',
      'Tòa tháp kết hợp truyền phát sóng, quan sát và du lịch trong cùng một công trình trên núi Namsan.',
      '10:00–22:30 ngày thường; 10:00–23:00 cuối tuần và ngày lễ; vào cửa muộn nhất 30 phút trước giờ đóng.',
      'Đài quan sát: người lớn 29.000 KRW, trẻ em 23.000 KRW; kiểm tra giá và ưu đãi mới nhất trước chuyến đi.',
      'Khoảng 2 giờ, chưa gồm thời gian đi cáp treo hoặc đi bộ lên núi.',
      'Cuối chiều để ngắm hoàng hôn và cảnh đêm; đến sớm vào cuối tuần.',
      'Có thang máy, lối tiếp cận, nhà vệ sinh phù hợp và dịch vụ xe lăn hoặc xe đẩy tại quầy thông tin.',
      'https://english.visitseoul.net/attractions/namsan-seoul-tower_/37', '2026-10-04'
    );

    insert into public.location_quick_facts (revision_id, label, value, display_order) values
      (revision_uuid, 'Mở cửa công chúng', '1980', 0),
      (revision_uuid, 'Độ cao tháp', '236,7 mét', 1),
      (revision_uuid, 'Địa chỉ', '105 Namsangongwon-gil, Yongsan-gu, Seoul', 2);

    insert into public.location_sources (revision_id, title, publisher, url, accessed_at, verification_status, verified_at, is_official, is_visible, display_order) values
      (revision_uuid, 'Namsan Seoul Tower', 'Visit Seoul', 'https://english.visitseoul.net/attractions/namsan-seoul-tower_/37', '2026-10-04', 'verified', '2026-10-04', true, true, 0),
      (revision_uuid, 'YTN Seoul Tower introduction', 'YTN Seoul Tower', 'https://www.seoultower.co.kr/en/intro/index', '2026-10-04', 'verified', '2026-10-04', true, true, 1),
      (revision_uuid, 'N Seoul Tower', 'Korea Tourism Organization', 'https://english.visitkorea.or.kr/svc/whereToGo/locIntrdn/rgnContentsView.do?menuSn=351&vcontsId=88026', '2026-10-04', 'verified', '2026-10-04', true, true, 2);

    insert into public.location_history (revision_id, period_label, title, short_description, long_description, related_people, categories, media_kind, media_url, media_credit, media_source_url, media_alt, fun_fact, display_order) values
      (revision_uuid, '1969–1971', 'Xây dựng tháp truyền phát trên Namsan', 'Tháp được xây dựng trên núi Namsan để phục vụ truyền phát sóng trong bối cảnh hạ tầng truyền thông Seoul phát triển nhanh.', 'Việc xây dựng tháp truyền phát trên đỉnh Namsan cho thấy cách hạ tầng kỹ thuật có thể trở thành một phần của cảnh quan đô thị. Vị trí cao giúp tín hiệu phủ rộng, đồng thời tạo điều kiện để công trình về sau phát triển thêm vai trò quan sát và du lịch. Khi học mốc này, hãy phân biệt chức năng ban đầu của tháp với những trải nghiệm dành cho khách tham quan được bổ sung sau đó.', null, array['xây dựng', 'truyền thông'], 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/N%20Seoul%20Tower%20%2813952097192%29.jpg', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:N_Seoul_Tower_(13952097192).jpg', 'Tháp Namsan Seoul nhìn từ xa', 'Tháp hoàn tất phần xây dựng trước khi mở cửa đón khách tham quan.', 0),
      (revision_uuid, '1975', 'Tháp bắt đầu truyền phát sóng', 'Namsan Seoul Tower trở thành một trong các hạ tầng truyền phát quan trọng, kết nối công nghệ phát thanh truyền hình với trung tâm Seoul.', 'Năm 1975 là mốc thường được gắn với sự ra đời của tháp như một công trình truyền phát. YTN Seoul Tower giới thiệu đây là tháp sóng tổng hợp đầu tiên của Hàn Quốc, được xây để thúc đẩy tương lai của ngành phát sóng và du lịch. Vai trò kỹ thuật này lý giải vì sao công trình có hình thức cao, dễ nhận biết và trở thành mốc định hướng quen thuộc trong thành phố.', null, array['truyền phát', 'công nghệ'], 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/N%20Seoul%20Tower%20%2813952097192%29.jpg', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:N_Seoul_Tower_(13952097192).jpg', 'Namsan Seoul Tower là một mốc cao trong đường chân trời Seoul', 'Tháp là công trình kết hợp kỹ thuật phát sóng và du lịch.', 1),
      (revision_uuid, '1980', 'Mở cửa đài quan sát cho công chúng', 'Sau khi mở cửa công chúng, tháp phát sóng trở thành điểm ngắm cảnh và biểu tượng du lịch được nhận biết rộng rãi của Seoul.', 'Việc mở cửa cho công chúng năm 1980 tạo thêm một lớp ý nghĩa mới cho công trình. Khách tham quan có thể đi lên cao để quan sát thành phố thay vì chỉ nhìn tháp từ xa. Theo Korea Tourism Organization, đây là tháp đa năng đầu tiên của Hàn Quốc kết hợp hiệu quả đài quan sát với tháp phát sóng. Sự kết hợp đó giải thích sức hấp dẫn bền vững của địa điểm đối với cả người dân Seoul và du khách quốc tế.', null, array['du lịch', 'đài quan sát'], 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/N%20Seoul%20Tower%20%2813952097192%29.jpg', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:N_Seoul_Tower_(13952097192).jpg', 'Tháp Namsan Seoul với đài quan sát cho khách tham quan', 'Đài quan sát mang lại góc nhìn 360 độ về Seoul.', 2),
      (revision_uuid, 'Hiện nay', 'Biểu tượng toàn cầu của Seoul hiện đại', 'Ngày nay, Namsan Seoul Tower là không gian văn hóa, cảnh quan và giải trí, gắn với núi Namsan và đường chân trời Seoul.', 'Ngày nay tháp được vận hành như một điểm đến nhiều tầng: khu plaza phía dưới có dịch vụ, còn các tầng cao có đài quan sát, cửa hàng và nhà hàng. Công trình thay đổi diện mạo theo ánh sáng và mùa, trong khi núi Namsan tạo bối cảnh xanh giữa thành phố dày đặc. Điều này giúp người học hiểu rằng một công trình kỹ thuật có thể trở thành biểu tượng văn hóa thông qua trải nghiệm công cộng, truyền thông và ký ức đô thị.', null, array['biểu tượng', 'đô thị'], 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/N%20Seoul%20Tower%20%2813952097192%29.jpg', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:N_Seoul_Tower_(13952097192).jpg', 'Tháp Namsan Seoul giữa cảnh quan đô thị', 'Tháp được chiếu sáng với các màu khác nhau vào ban đêm.', 3);

    insert into public.location_highlights (revision_id, name, korean_name, tagline, short_description, long_description, address, activities, fun_fact, categories, media_kind, media_url, media_credit, media_source_url, media_alt, display_order) values
      (revision_uuid, 'Đài quan sát', '전망대', 'Góc nhìn 360 độ về Seoul', 'Đài quan sát ở các tầng cao là nơi xem đường chân trời Seoul, núi bao quanh và sự thay đổi của thành phố từ ngày sang đêm.', 'Đài quan sát là điểm nhấn chính của Namsan Seoul Tower. Từ độ cao trên núi Namsan, khách có thể quan sát thành phố theo nhiều hướng và nhận ra mối liên hệ giữa sông, núi, khu trung tâm cùng các quận dân cư. Hãy dành thời gian nhìn bảng chỉ hướng, quan sát lúc ánh sáng thay đổi và tôn trọng không gian chung khi chụp ảnh. Thời gian vào cửa và giá vé thay đổi theo chính sách vận hành nên cần kiểm tra trước chuyến đi.', 'T5–T7, Namsan Seoul Tower', array['Ngắm toàn cảnh', 'Tìm địa danh trên đường chân trời'], 'Đài quan sát có thể mở muộn hơn khu plaza phía dưới.', array['quan sát', 'cảnh quan'], 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/N%20Seoul%20Tower%20%2813952097192%29.jpg', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:N_Seoul_Tower_(13952097192).jpg', 'Tháp Namsan Seoul với đài quan sát', 0),
      (revision_uuid, 'Namsan Seoul Tower Plaza', '서울타워플라자', 'Không gian dịch vụ dưới chân tháp', 'Khu plaza ở các tầng thấp có không gian nghỉ, cửa hàng, nhà hàng và điểm khởi đầu thuận tiện trước khi lên đài quan sát.', 'Seoul Tower Plaza giúp chuyến tham quan có nhịp độ linh hoạt hơn: người đi bộ hoặc đi xe buýt có thể nghỉ, tìm thông tin và sử dụng dịch vụ trước khi tiếp tục lên các tầng cao. Theo Visit Seoul, khu plaza nằm từ tầng một đến tầng bốn, tách với khu N Seoul Tower từ tầng năm trở lên. Khi đông khách, hãy hẹn điểm gặp rõ ràng và dành thêm thời gian cho thang máy hoặc xếp hàng.', 'Tầng 1–4, Namsan Seoul Tower', array['Nghỉ chân', 'Tìm thông tin', 'Ăn uống'], 'Plaza và đài quan sát là hai phần không gian chính của điểm đến.', array['dịch vụ', 'không gian công cộng'], 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/N%20Seoul%20Tower%20%2813952097192%29.jpg', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:N_Seoul_Tower_(13952097192).jpg', 'Khu tháp Namsan Seoul dành cho khách tham quan', 1),
      (revision_uuid, 'Núi Namsan', '남산', 'Mảng xanh giữa đô thị Seoul', 'Núi Namsan cung cấp đường đi bộ, không khí ngoài trời và bối cảnh tự nhiên cho tháp, giúp chuyến tham quan không chỉ xoay quanh công trình.', 'Namsan là nền cảnh quan quyết định trải nghiệm tại tháp. Các tuyến đi bộ cho phép khách tiếp cận chậm hơn, quan sát cây xanh, độ dốc và góc nhìn thay đổi dần khi lên cao. Trang chính thức giới thiệu nhiều điểm xuất phát với thời gian đi bộ khoảng ba mươi đến bốn mươi phút. Hãy mang nước, chọn giày phù hợp và cân nhắc thời tiết. Không rời khỏi lối đi được chỉ dẫn hoặc để lại rác trong công viên.', 'Namsan Park, Yongsan-gu, Seoul', array['Đi bộ', 'Quan sát thiên nhiên', 'Chụp ảnh'], 'Namsan giúp tháp đạt độ cao quan sát đáng kể so với mực nước biển.', array['công viên', 'đi bộ'], 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/N%20Seoul%20Tower%20%2813952097192%29.jpg', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:N_Seoul_Tower_(13952097192).jpg', 'Tháp Namsan Seoul trên đỉnh núi Namsan', 2),
      (revision_uuid, 'Cáp treo Namsan', '남산 케이블카', 'Lên núi bằng tuyến cáp treo', 'Cáp treo nối khu chân núi với điểm gần tháp, là lựa chọn thay thế cho việc đi bộ hoặc xe buýt vòng Namsan.', 'Cáp treo là một cách phổ biến để tiếp cận khu tháp và quan sát sườn núi trong khi di chuyển. Trang YTN Seoul Tower hướng dẫn đi từ ga Myeongdong qua thang cuốn ngoài trời đến ga cáp treo, với thời gian đi khoảng mười lăm phút. Cáp treo có lịch vận hành riêng và có thể tạm dừng kiểm tra, vì vậy hãy kiểm tra giờ thực tế trước khi đi. Đừng nhầm giá cáp treo với vé đài quan sát.', 'Namsan Cable Car, Yongsan-gu, Seoul', array['Đi cáp treo', 'Quan sát sườn núi'], 'Cáp treo thường vận hành từ 10:00 đến 23:00, tùy thông báo trong ngày.', array['di chuyển', 'cảnh quan'], 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/N%20Seoul%20Tower%20%2813952097192%29.jpg', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:N_Seoul_Tower_(13952097192).jpg', 'Tháp Namsan Seoul và tuyến tiếp cận từ công viên', 3);

    insert into public.location_experiences (revision_id, name, korean_name, short_description, long_description, origin_meaning, recognizable_features, dos, donts, related_experience, media_kind, media_url, media_credit, media_source_url, media_alt, display_order) values
      (revision_uuid, 'Ngắm hoàng hôn và cảnh đêm', '야경 감상', 'Quan sát Seoul chuyển từ ánh sáng ban ngày sang đường chân trời rực sáng là trải nghiệm đặc trưng tại đài quan sát và khu vực Namsan.', 'Hoàng hôn và cảnh đêm giúp người tham quan nhận ra một thành phố thay đổi nhanh theo ánh sáng. Đến sớm giúp có thời gian qua kiểm tra vé, thang máy và chọn góc quan sát phù hợp. Dùng kính hoặc máy ảnh gọn nhẹ, giảm ánh sáng màn hình và nhường vị trí cửa sổ cho người khác. Nếu thời tiết xấu hoặc tầm nhìn hạn chế, hãy chuyển trọng tâm sang tìm hiểu về tháp, công viên và lịch sử truyền phát thay vì cố chờ một khung hình hoàn hảo.', 'Trải nghiệm cảnh quan đô thị từ độ cao Namsan', array['Toàn cảnh', 'Cảnh đêm', 'Đường chân trời'], array['Kiểm tra thời tiết', 'Đến sớm'], array['Không chen lấn', 'Không dùng đèn flash gây chói'], 'Kết hợp với đài quan sát và công viên Namsan', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/N%20Seoul%20Tower%20%2813952097192%29.jpg', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:N_Seoul_Tower_(13952097192).jpg', 'Namsan Seoul Tower vào thời điểm ngắm cảnh', 0),
      (revision_uuid, 'Đi bộ đường mòn Namsan', '남산 산책', 'Đi bộ lên núi giúp cảm nhận sự chuyển tiếp từ phố xá Seoul đến công viên, trước khi tiếp cận tháp và plaza.', 'Đi bộ là cách chậm rãi để trải nghiệm núi Namsan và nhìn tháp dần xuất hiện trong cảnh quan. Các tuyến từ Thư viện Công cộng Namsan, Nhà hát Quốc gia hoặc khu Sam-soon Steps có thời lượng khác nhau. Hãy chọn đường phù hợp thể lực, mang nước và tôn trọng biển chỉ dẫn. Không bỏ lại rác, không đi vào khu vực hạn chế và nên quay lại khi thời tiết chuyển xấu. Trải nghiệm này bổ sung cho chuyến lên đài quan sát bằng một câu chuyện rõ ràng hơn về địa hình và công viên.', 'Khám phá Namsan bằng lối đi công cộng', array['Đường mòn', 'Cây xanh', 'Độ dốc'], array['Mang nước', 'Đi giày phù hợp'], array['Không rời đường mòn', 'Không xả rác'], 'Kết hợp với plaza và đài quan sát', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/N%20Seoul%20Tower%20%2813952097192%29.jpg', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:N_Seoul_Tower_(13952097192).jpg', 'Tháp Namsan Seoul trong không gian công viên', 1),
      (revision_uuid, 'Chụp ảnh khóa tình yêu', '사랑의 자물쇠', 'Khu khóa tình yêu là chi tiết văn hóa đại chúng gắn với Namsan, thường được du khách dùng để ghi lại kỷ niệm cùng bạn bè hoặc người thân.', 'Khóa tình yêu là một trải nghiệm mang tính biểu tượng đại chúng tại Namsan Seoul Tower. Hãy xem nó như một câu chuyện về cách một địa danh hiện đại tạo ra nghi thức du lịch mới, không phải một yêu cầu bắt buộc khi ghé thăm. Nếu tham gia, tuân thủ vị trí được cho phép và tránh gắn vật dụng lên cây, lan can an toàn hoặc cấu kiện không dành cho khóa. Chụp ảnh, đi dạo và quan sát cảnh quan cũng là cách trải nghiệm trọn vẹn mà không tạo thêm rác hoặc cản trở người khác.', 'Nghi thức du lịch đương đại quanh Namsan Seoul Tower', array['Ổ khóa', 'Hàng rào chỉ định', 'Ảnh kỷ niệm'], array['Dùng khu vực cho phép', 'Giữ lối đi thông thoáng'], array['Không khóa vào cây', 'Không vứt khóa xuống công viên'], 'Kết hợp với chuyến đi bộ và cảnh đêm', 'image', 'https://commons.wikimedia.org/wiki/Special:FilePath/N%20Seoul%20Tower%20%2813952097192%29.jpg', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:N_Seoul_Tower_(13952097192).jpg', 'Namsan Seoul Tower là điểm hẹn văn hóa đại chúng', 2);

    insert into public.location_foods (revision_id, name, korean_name, short_description, long_description, ingredients, flavors, special_feature, experience_places, image_url, image_credit, image_source_url, image_alt, display_order) values
      (revision_uuid, 'Cà phê và đồ uống nóng', '커피와 음료', 'Các quán cà phê tại khu tháp là điểm nghỉ phù hợp sau khi đi bộ Namsan hoặc trước khi tiếp tục lên đài quan sát.', 'Đồ uống nóng hoặc lạnh tại khu plaza và tháp giúp khách điều chỉnh nhịp tham quan, nhất là trong thời tiết lạnh hoặc khi phải chờ thang máy. Hãy xem menu, hỏi thành phần nếu có dị ứng và giữ đồ uống trong khu vực được phép. Trải nghiệm này liên quan đến việc nghỉ ngơi tại điểm đến hơn là một món truyền thống riêng của Namsan. Các cửa hàng và menu có thể thay đổi theo thời gian nên không nên coi đây là danh sách cố định.', array['cà phê', 'trà', 'sữa'], array['đắng', 'ngọt', 'ấm'], 'Khu tháp có nhà hàng và quán cà phê ở nhiều tầng.', array['Seoul Tower Plaza', 'N Seoul Tower'], 'https://commons.wikimedia.org/wiki/Special:FilePath/N%20Seoul%20Tower%20%2813952097192%29.jpg', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:N_Seoul_Tower_(13952097192).jpg', 'Namsan Seoul Tower với các dịch vụ ăn uống', 0),
      (revision_uuid, 'Bữa ăn Hàn Quốc', '한식 식사', 'Nhà hàng tại khu tháp là nơi kết hợp bữa ăn với trải nghiệm cảnh quan Seoul, phù hợp cho một điểm dừng dài hơn trong hành trình.', 'Ẩm thực tại khu tháp thay đổi theo từng nhà hàng và mùa, vì vậy dữ liệu này giới thiệu loại trải nghiệm thay vì khẳng định một thực đơn cố định. Một bữa ăn Hàn Quốc thường kết hợp cơm, món chính, món phụ và canh hoặc súp. Khi đi theo nhóm, hãy kiểm tra thời gian phục vụ, đặt chỗ nếu cần và hỏi về lựa chọn chay hoặc dị ứng. Nhà hàng có thể đông vào cuối tuần hoặc khung giờ ngắm hoàng hôn, vì vậy hãy giữ lịch trình linh hoạt.', array['cơm', 'món phụ', 'rau', 'súp'], array['mặn', 'ấm', 'đa dạng'], 'Bữa ăn gắn với góc nhìn thành phố từ khu tháp.', array['Seoul Tower Plaza', 'Nhà hàng trên tháp'], 'https://commons.wikimedia.org/wiki/Special:FilePath/N%20Seoul%20Tower%20%2813952097192%29.jpg', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:N_Seoul_Tower_(13952097192).jpg', 'Tháp Namsan Seoul là điểm có nhà hàng và quán cà phê', 1),
      (revision_uuid, 'Tráng miệng và đồ ngọt', '디저트', 'Đồ ngọt và món tráng miệng là lựa chọn nhẹ cho thời gian nghỉ giữa các khu plaza, công viên và đài quan sát.', 'Một món tráng miệng hoặc đồ ngọt có thể phù hợp khi khách muốn nghỉ ngắn thay vì dùng bữa đầy đủ. Lựa chọn cụ thể phụ thuộc cửa hàng đang hoạt động, vì thế hãy đọc menu tại chỗ. Khi mang thực phẩm ngoài trời, tuân thủ khu vực được phép và thu gom bao bì trước khi trở lại công viên. Cách tiếp cận có trách nhiệm giúp trải nghiệm cảnh quan không tạo thêm rác cho núi Namsan và các lối đi chung.', array['bột', 'đường', 'sữa hoặc trái cây'], array['ngọt', 'mát', 'thơm'], 'Menu thay đổi theo cửa hàng và mùa.', array['Seoul Tower Plaza', 'Khu dịch vụ N Seoul Tower'], 'https://commons.wikimedia.org/wiki/Special:FilePath/N%20Seoul%20Tower%20%2813952097192%29.jpg', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:N_Seoul_Tower_(13952097192).jpg', 'Khu Namsan Seoul Tower phục vụ khách tham quan', 2);

    insert into public.location_fun_facts (revision_id, title, category, fact, icon_name, unlock_after_stage, display_order) values
      (revision_uuid, 'Hai độ cao cộng lại', 'Địa lý', 'Tháp cao khoảng 236,7 mét và nằm trên núi Namsan cao khoảng 243 mét, tạo độ cao quan sát gần 480 mét so với mực nước biển.', 'height', 1, 0),
      (revision_uuid, 'Tháp đa năng đầu tiên', 'Công nghệ', 'Korea Tourism Organization giới thiệu Namsan Seoul Tower là tháp đa năng đầu tiên ở Hàn Quốc, kết hợp đài quan sát với tháp phát sóng.', 'settings_input_antenna', 3, 1),
      (revision_uuid, 'Mở cửa quanh năm', 'Du lịch', 'Theo Visit Seoul và trang vận hành, tháp mở cửa hằng ngày quanh năm; giờ đóng cửa thay đổi giữa ngày thường và cuối tuần.', 'calendar_month', 5, 2),
      (revision_uuid, 'Màu sắc ban đêm', 'Cảnh quan', 'Ánh sáng ban đêm khiến Namsan Seoul Tower thay đổi diện mạo trong đường chân trời, tạo một điểm nhận biết quen thuộc của Seoul.', 'nightlight', 6, 3);

    insert into public.location_transport_options (revision_id, mode, title, instructions, tip, is_recommended, display_order) values
      (revision_uuid, 'bus', 'Xe buýt vòng Namsan 01', 'Từ ga Chungmuro tuyến 3 hoặc 4, cửa ra 2, đón xe buýt Namsan Circular 01 và xuống trạm Namsan Seoul Tower.', 'Đây là lựa chọn thuận tiện nếu không muốn đi bộ dốc hoặc đi cáp treo.', true, 0),
      (revision_uuid, 'other', 'Cáp treo Namsan', 'Từ Myeongdong, đi bộ đến thang cuốn ngoài trời Namsan rồi đến ga cáp treo để tiếp cận khu tháp.', 'Cáp treo có lịch riêng; kiểm tra bảo trì và giá vé trước chuyến đi.', false, 1),
      (revision_uuid, 'walk', 'Đi bộ đường mòn Namsan', 'Chọn tuyến từ Thư viện Công cộng Namsan, Nhà hát Quốc gia hoặc Sam-soon Steps; thời gian thường khoảng 30–40 phút.', 'Phù hợp khi thời tiết tốt và có giày đi bộ thoải mái.', false, 2);

    insert into public.location_visitor_notes (revision_id, content, display_order) values
      (revision_uuid, 'Ô tô thông thường bị hạn chế vào khu tháp; ưu tiên xe buýt xanh, cáp treo hoặc đi bộ.', 0),
      (revision_uuid, 'Không hút thuốc trong khu vực thuộc Công viên Quốc gia; vi phạm có thể bị phạt theo thông báo vận hành.', 1),
      (revision_uuid, 'Kiểm tra thời tiết, giờ hoạt động, giá vé và lịch bảo trì chính thức trước khi khởi hành.', 2);

    insert into public.quiz_questions (id, revision_id, kind, prompt, explanation, is_visible, display_order) values
      ('00000000-0000-4000-8000-000000000501', revision_uuid, 'single_choice', 'Namsan Seoul Tower mở cửa cho công chúng vào năm nào?', 'Tháp mở cửa cho công chúng năm 1980. Trước đó công trình được xây để phục vụ truyền phát sóng, sau đó bổ sung vai trò đài quan sát và điểm du lịch.', true, 0),
      ('00000000-0000-4000-8000-000000000502', revision_uuid, 'single_choice', 'Namsan Seoul Tower kết hợp hai chức năng chính nào?', 'Địa điểm kết hợp tháp truyền phát sóng và đài quan sát. Chính sự kết hợp này khiến công trình vừa có ý nghĩa công nghệ, vừa là điểm đến du lịch.', true, 1),
      ('00000000-0000-4000-8000-000000000503', revision_uuid, 'single_choice', 'Namsan Seoul Tower nằm trên ngọn núi nào?', 'Tháp nằm trên núi Namsan ở trung tâm Seoul. Độ cao của núi làm tăng tầm nhìn và tạo bối cảnh công viên xanh cho công trình.', true, 2),
      ('00000000-0000-4000-8000-000000000504', revision_uuid, 'single_choice', 'Độ cao kiến trúc của tháp xấp xỉ bao nhiêu?', 'Độ cao kiến trúc thường được nêu khoảng 236,7 mét. Khi cộng với độ cao núi Namsan, điểm quan sát đạt gần 480 mét so với mực nước biển.', true, 3),
      ('00000000-0000-4000-8000-000000000505', revision_uuid, 'single_choice', 'Khu Seoul Tower Plaza thường nằm ở những tầng nào?', 'Visit Seoul mô tả Seoul Tower Plaza ở các tầng thấp, từ tầng một đến tầng bốn, trong khi khu N Seoul Tower bắt đầu từ tầng năm.', true, 4),
      ('00000000-0000-4000-8000-000000000506', revision_uuid, 'single_choice', 'Phương tiện nào được khuyến nghị để đến gần tháp thay cho ô tô thường?', 'Xe buýt vòng Namsan 01 là lựa chọn công cộng được Visit Seoul hướng dẫn. Ô tô thường bị hạn chế vào khu vực tháp để giảm tác động giao thông.', true, 5),
      ('00000000-0000-4000-8000-000000000507', revision_uuid, 'single_choice', 'Cáp treo Namsan thường đi từ khu vực ga nào?', 'Trang vận hành hướng dẫn tiếp cận cáp treo từ khu Myeongdong, qua thang cuốn ngoài trời Namsan đến ga cáp treo.', true, 6),
      ('00000000-0000-4000-8000-000000000508', revision_uuid, 'single_choice', 'Khách nên làm gì trước khi lên đài quan sát vào cuối tuần?', 'Cuối tuần thường đông hơn, vì vậy nên đến sớm và kiểm tra giờ hoạt động, thời tiết cũng như thời gian chờ thang máy trước khi mua vé.', true, 7),
      ('00000000-0000-4000-8000-000000000509', revision_uuid, 'single_choice', 'Một quy tắc ứng xử đúng tại Namsan là gì?', 'Người tham quan nên đi theo lối chỉ dẫn, giữ sạch công viên và không gắn vật dụng lên cây hoặc cấu kiện không được phép. Điều này bảo vệ cảnh quan chung.', true, 8),
      ('00000000-0000-4000-8000-000000000510', revision_uuid, 'single_choice', 'Vì sao cảnh đêm là trải nghiệm nổi bật tại tháp?', 'Từ độ cao Namsan, khách có thể quan sát Seoul chuyển từ ánh sáng ban ngày sang cảnh đêm. Cảnh quan thay đổi này là một nét hấp dẫn của địa điểm.', true, 9);

    insert into public.quiz_options (question_id, option_text, is_correct, display_order) values
      ('00000000-0000-4000-8000-000000000501', '1971', false, 0), ('00000000-0000-4000-8000-000000000501', '1975', false, 1), ('00000000-0000-4000-8000-000000000501', '1980', true, 2), ('00000000-0000-4000-8000-000000000501', '2005', false, 3),
      ('00000000-0000-4000-8000-000000000502', 'Tháp phát sóng và đài quan sát', true, 0), ('00000000-0000-4000-8000-000000000502', 'Cung điện và bảo tàng', false, 1), ('00000000-0000-4000-8000-000000000502', 'Sân bay và nhà ga', false, 2), ('00000000-0000-4000-8000-000000000502', 'Thư viện và trường học', false, 3),
      ('00000000-0000-4000-8000-000000000503', 'Namsan', true, 0), ('00000000-0000-4000-8000-000000000503', 'Bukhansan', false, 1), ('00000000-0000-4000-8000-000000000503', 'Hallasan', false, 2), ('00000000-0000-4000-8000-000000000503', 'Seoraksan', false, 3),
      ('00000000-0000-4000-8000-000000000504', '63 mét', false, 0), ('00000000-0000-4000-8000-000000000504', '236,7 mét', true, 1), ('00000000-0000-4000-8000-000000000504', '555 mét', false, 2), ('00000000-0000-4000-8000-000000000504', '1.000 mét', false, 3),
      ('00000000-0000-4000-8000-000000000505', 'Tầng 1–4', true, 0), ('00000000-0000-4000-8000-000000000505', 'Tầng T5–T7', false, 1), ('00000000-0000-4000-8000-000000000505', 'Chỉ tầng hầm', false, 2), ('00000000-0000-4000-8000-000000000505', 'Chỉ tầng mái', false, 3),
      ('00000000-0000-4000-8000-000000000506', 'Xe buýt vòng Namsan 01', true, 0), ('00000000-0000-4000-8000-000000000506', 'Xe tải giao hàng', false, 1), ('00000000-0000-4000-8000-000000000506', 'Ô tô thường', false, 2), ('00000000-0000-4000-8000-000000000506', 'Tàu cao tốc', false, 3),
      ('00000000-0000-4000-8000-000000000507', 'Myeongdong', true, 0), ('00000000-0000-4000-8000-000000000507', 'Incheon', false, 1), ('00000000-0000-4000-8000-000000000507', 'Gangnam', false, 2), ('00000000-0000-4000-8000-000000000507', 'Jamsil', false, 3),
      ('00000000-0000-4000-8000-000000000508', 'Đến sớm và kiểm tra lịch vận hành', true, 0), ('00000000-0000-4000-8000-000000000508', 'Bỏ qua thông tin thời tiết', false, 1), ('00000000-0000-4000-8000-000000000508', 'Đậu ô tô tại tháp', false, 2), ('00000000-0000-4000-8000-000000000508', 'Đi vào khu hạn chế', false, 3),
      ('00000000-0000-4000-8000-000000000509', 'Giữ sạch công viên và đi theo lối chỉ dẫn', true, 0), ('00000000-0000-4000-8000-000000000509', 'Gắn khóa lên cây', false, 1), ('00000000-0000-4000-8000-000000000509', 'Hút thuốc trong công viên', false, 2), ('00000000-0000-4000-8000-000000000509', 'Rời khỏi đường mòn', false, 3),
      ('00000000-0000-4000-8000-000000000510', 'Toàn cảnh thành phố đổi theo ánh sáng', true, 0), ('00000000-0000-4000-8000-000000000510', 'Tháp đóng cửa lúc hoàng hôn', false, 1), ('00000000-0000-4000-8000-000000000510', 'Không có núi xung quanh', false, 2), ('00000000-0000-4000-8000-000000000510', 'Chỉ dành cho phát sóng', false, 3);
  end if;
end;
$$;

